### ISSUE TITLE
Can't create or use variables with "earmuffs" on their names.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [shikantaza/pLisp#29]
The form I was trying to compile was a very ordinary Lisp form:

    (defun test ()
        *variable-with-earmuffs*)

This was parsed as:

    (defun test ()
         * variable-with-earmuffs *)

The error also occurs when trying to define the variable, but it's more subtle. It says "Undefined variable: VARIABLE-WITH-EARMUFFS".

**Comment by shikantaza** [comment]
At present the lexer assumes that symbols will comprise only alphanumeric characters (and '-'). Since there are no special variables in pLisp per se, I didn't include support for symbols with '*'.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
That must be why you decided to call it `call-cc` when everybody else calls it `call/cc`. I've just discovered that trying to evaluate `(define x/y 1)` is enough to crash pLisp.

**Comment by shikantaza** [comment]
Oops, I'll fix that.

**Comment by shikantaza** [comment]
Added validation to catch invalid expressions like '(define x/y 1). Closing issue.

**Comment by heegaiximephoomeeghahyaiseekh** [comment]
This bug also means you can't define `let*`, `list*`, or a number of other Lisp operators in pLisp.

**Comment by shikantaza** [comment]
Yeah, I actually have a let1 that's functionally equivalent to LET*.

This is an artifact of a design decision taken a long time ago, adding '*' to the allowed characters in a symbol should not be too difficult.
