### ISSUE TITLE
pLisp crashes, burns, and tries to take the whole system down with it when attempting to load Common Lisp code

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [shikantaza/pLisp#31]
The source file in question is found in
[this attachment](https://github.com/shikantaza/pLisp/files/222572/loop.zip). It's an old implementation of the LOOP macro.

Warning: Be prepared to reboot your system.

To crash your system, enter this into the listener:

    (load-file "loop.cl")

pLisp throws an error because `in-package` isn't defined, as it very well should. But when you click OK on the dialog box that appears, the debugger window appears, and then pLisp goes on its merry way trying to load the rest of the file in the background. New debugger windows appear each time you click OK on an error dialog, and in the blink of an eye, all available RAM is consumed. My system thrashed for an hour before the kernel finally killed pLisp.

**Comment by shikantaza** [comment]
Thanks, I'll look into this.

**Comment by shikantaza** [comment]
I have added an additional check to ensure that parsing the next expression from the file will happen only if the previous expression doesn't produce an exception. Have pushed the changes to the repository, closing the issue. Thanks!
