### ISSUE TITLE
Unexpected behavior when mixing TRY with UNWIND-PROTECT

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [shikantaza/pLisp#32]
This shouldn't produce any error dialogs, but it does:

```
(try (unwind-protect (car 1)
        (print "Unwind-protect exiting!"))
    (catch (e) nil)
    (print "Finally"))
```

**Comment by shikantaza** [comment]
The 'try' macro had variable capture issues. Have fixed these and have pushed the changes, closing the issue. Thanks.
