### ISSUE TITLE
Workspace becomes unusable after attempting to evaluate an expression.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [shikantaza/pLisp#38]
After evaluating an expression in the Workspace window using Ctrl+Enter, the window becomes unusable (producing a beep on every keystroke) until you move the focus to another window and back. This is really annoying.

**Comment by shikantaza** [comment]
I want to simulate the behaviour of the REPL and display the results of the evaluation to the user  without any effort on their part, by transferring the focus to the Transcript window. Hence the need to explicitly bring the focus back to the Workspace. I am open to suggestions vis-a-vis the most user-friendly and preferred way to do this.

**Comment by shikantaza** [comment]
The way I've been using pLisp is: type expression in Workspace -> see results pop up in Transcript -> Alt Tab -> type next expression in workspace ->...

I assumed this mode of operation would be the natural one, am willing to change this to a better way of doing things if possible.

**Comment by shikantaza** [comment]
On second thought, leaving the focus in the workspace seems like a reasonable thing to do. The user can have the transcript window open side-by-side to see the results of the evaluation. I have pushed these changes, closing the issue.
