### ISSUE TITLE
Built-in functions are not exposed as pLisp functions.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [shikantaza/pLisp#39]
...which means you can't do really simple things such as:

    (apply + a-list-of-numbers)

or:

    (mapcar car a-list-of-conses)

To add insult to injury, when I tried to define `++` as a function that implemented `+` with `eval`, pLisp crashed, since pLisp's reader still treats math operators specially instead of them just being regular symbols, like they are in all other Lisps. I see you can still have `+` as a symbol name, though.

**Comment by shikantaza** [comment]
This and #40 are related and are due to the way the compiler is implemented. I need to dig into what changes to the compiler will allow me to use built-ins in all the places where a user-defined function can be used.

**Comment by shikantaza** [comment]
I have made changes such that primitives/built-in functions can now be used in the same way user-defined functions are used (apply, funcall, map, etc). Closing the issue. **Please ensure that you use the new image (supplied as part of the tarball) to see these new definitions**. Thanks.

(The identifier-related restrictions have also been removed -- except for special characters like , ( ) [ ] '`@ : ". all other characters from the Common Lisp standard character list can now be used in identifiers)
