### ISSUE TITLE
"Expression contains special operator in an operand position"

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [shikantaza/pLisp#40]
The expression:

    (defun car-fn (cons)
        (eval (list 'car cons)))

Apparently, my naming a variable `cons` is what triggers this error. It's very strange that pLisp checks the names of my variables and has reserved words like some Pascal dialect. In other Lisps, even the most fundamental builtins aren't reserved words. For example, in every Lisp dialect that I know of except pLisp, this is a legal expression:

    (let ((lambda 1))
      lambda) ;; => 1

**Comment by shikantaza** [comment]
Please see my comment for #39.

**Comment by shikantaza** [comment]
Have made changes such that there is now no conflict between built-in names and the variables defined by the user (i.e., expressions like '(let ((lambda 1)) lambda)' will work fine. Closing the issue.
